CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE
);


INSERT INTO users (name, email) VALUES
('John Doe', 'johndoe@example.com'),
('Jane Smith', 'janesmith@example.com'),
('Alice Johnson', 'alicejohnson@example.com'),
('Bob Williams', 'bobwilliams@example.com'),
('Emma Brown', 'emmabrown@example.com'),
('Michael Davis', 'michaeldavis@example.com'),
('Olivia Miller', 'oliviamiller@example.com'),
('William Wilson', 'williamwilson@example.com'),
('Sophia Moore', 'sophiamoore@example.com'),
('James Taylor', 'jamestaylor@example.com'),
('Emily Anderson', 'emilyanderson@example.com'),
('Daniel Thomas', 'danielthomas@example.com'),
('Ava Jackson', 'avajackson@example.com'),
('David White', 'davidwhite@example.com'),
('Mia Harris', 'miaharris@example.com'),
('Joseph Martin', 'josephmartin@example.com'),
('Charlotte Thompson', 'charlottethompson@example.com'),
('Christopher Garcia', 'christophergarcia@example.com'),
('Amelia Martinez', 'ameliamartinez@example.com'),
('Andrew Robinson', 'andrewrobinson@example.com'),
('Elizabeth Clark', 'elizabethclark@example.com'),
('Matthew Rodriguez', 'matthewrodriguez@example.com'),
('Sofia Lewis', 'sofialewis@example.com'),
('Joshua Lee', 'joshualee@example.com'),
('Avery Walker', 'averywalker@example.com'),
('Ryan Hall', 'ryanhall@example.com'),
('Grace Allen', 'graceallen@example.com'),
('Kevin Young', 'kevinyoung@example.com'),
('Chloe Hernandez', 'chloehernandez@example.com'),
('Nicholas King', 'nicholasking@example.com'),
('Zoe Wright', 'zoewright@example.com'),
('Tyler Scott', 'tylerscott@example.com'),
('Hannah Green', 'hannahgreen@example.com'),
('Samuel Baker', 'samuelbaker@example.com'),
('Lily Adams', 'lilyadams@example.com'),
('Benjamin Nelson', 'benjaminnelson@example.com'),
('Aria Hill', 'ariahill@example.com'),
('Christopher Mitchell', 'christophermitchell@example.com'),
('Layla Carter', 'laylacarter@example.com'),
('Jonathan Phillips', 'jonathanphillips@example.com');
